// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmXcPw5WcgTdI2-VhOSV0j9uLaZSfh9-Y',
    appId: '1:805818188042:web:c53d01a700e39c5e583af3',
    messagingSenderId: '805818188042',
    projectId: 'firstproject1-6241a',
    authDomain: 'firstproject1-6241a.firebaseapp.com',
    databaseURL: 'https://firstproject1-6241a.firebaseio.com',
    storageBucket: 'firstproject1-6241a.appspot.com',
    measurementId: 'G-1PW21RT7KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtaCm7BjbdZ6_v-2cdUcZZpxX9M2YYhi8',
    appId: '1:805818188042:android:0f2298a1a8b86c2b583af3',
    messagingSenderId: '805818188042',
    projectId: 'firstproject1-6241a',
    databaseURL: 'https://firstproject1-6241a.firebaseio.com',
    storageBucket: 'firstproject1-6241a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXFoUl5VWHPzIyvbiBY7xUGZ7n7DN6Tp4',
    appId: '1:805818188042:ios:abad7f715cc3dc05583af3',
    messagingSenderId: '805818188042',
    projectId: 'firstproject1-6241a',
    databaseURL: 'https://firstproject1-6241a.firebaseio.com',
    storageBucket: 'firstproject1-6241a.appspot.com',
    iosClientId: '805818188042-o6l4puf3107nus7v6eh35kbrtb0f6nnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXFoUl5VWHPzIyvbiBY7xUGZ7n7DN6Tp4',
    appId: '1:805818188042:ios:abad7f715cc3dc05583af3',
    messagingSenderId: '805818188042',
    projectId: 'firstproject1-6241a',
    databaseURL: 'https://firstproject1-6241a.firebaseio.com',
    storageBucket: 'firstproject1-6241a.appspot.com',
    iosClientId: '805818188042-o6l4puf3107nus7v6eh35kbrtb0f6nnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingUser',
  );
}
